image: node:14-buster

cache: &global_cache
  key: ${CI_PROJECT_PATH_SLUG}
  paths:
    - node_modules/

.job_template: &test-configuration
  stage: test
  tags:
    - docker
  before_script:
    - apt-get update && apt-get install -y netcat
    - npm install
    - RUNNER_COUNT=16
    - FILES=( $(find -H -L ./test/* -regex "^.*.test.js") )
    - len=${#FILES[@]}
    - >
      for (( i=0; i<${RUNNER_COUNT}; i+=1 )); do
          RUNNER_TEST_CNTS[$i]=0
      done
    - >
      for (( i=0; i<${len}; i+=1 )); do
          TestCases[$i]=$(grep -o " it" ${FILES[$i]} | wc -l)
      done
    - >
      for ((i = 0; i<${len}; i++))
      do
          for((j = 0; j<${len}-i-1; j++))
          do
              if [ ${TestCases[j]} -lt ${TestCases[$((j+1))]} ]
              then
                  # swap
                  temp=${TestCases[j]}
                  TestCases[$j]=${TestCases[$((j+1))]}
                  TestCases[$((j+1))]=$temp

                  temp=${FILES[j]}
                  FILES[$j]=${FILES[$((j+1))]}
                  FILES[$((j+1))]=$temp
              fi
          done
      done
    - MIN=${RUNNER_TEST_CNTS[0]}
    - MINIDX=0
    - >
      for (( i=0; i<${len}; i+=1 )); do
          for j in ${!RUNNER_TEST_CNTS[@]};
          do
              if [ ${MIN} -gt ${RUNNER_TEST_CNTS[$j]} ]
              then
                  MIN=${RUNNER_TEST_CNTS[${j}]}
                  MINIDX=${j}
              fi
          done

          UNITTEST_FILES[$MINIDX]+=' '"${FILES[$i]}"
          RUNNER_TEST_CNTS[$MINIDX]=`expr ${TestCases[$i]} + ${RUNNER_TEST_CNTS[$MINIDX]}`
          MIN=${RUNNER_TEST_CNTS[$MINIDX]}
      done

  dependencies:
    - build

.job_template: &certora-configuration
  stage: certora
  image: 376433862203.dkr.ecr.us-east-1.amazonaws.com/certora-ci-base:latest
  tags:
    - docker
  allow_failure: true
  before_script:
    - ./specs/scripts/applyHarnesses.sh
  dependencies:
    - build

stages:
  - build
  - test
  - certora

build:
  stage: build
  tags:
    - docker
  script:
  - npm install
  - npm run build

# Test Stage
test_0:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[0]}

test_1:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[1]}

test_2:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[2]}

test_3:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[3]}

test_4:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[4]}

test_5:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[5]}

test_6:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[6]}

test_7:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[7]}

test_8:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[8]}

test_9:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[9]}

test_10:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[10]}

test_11:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[11]}

test_12:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[12]}

test_13:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[13]}

test_14:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[14]}

test_15:
  <<: *test-configuration
  script:
    - npm run test ${UNITTEST_FILES[15]}

# Certora Prover CI
certora_develop:
  <<: *certora-configuration
  script:
    - python3 scripts/certora_ci.py -r diff
  rules: # Trigger it when merge to develop branch
    - if: '$CI_COMMIT_TITLE =~ /^Merge branch/ && $CI_COMMIT_BRANCH == "develop"'

certora_release:
  <<: *certora-configuration
  script:
    - python3 scripts/certora_ci.py -r all
  rules: # Trigger it when checkout release branch
    - if: '$CI_COMMIT_BRANCH =~ /^release/ && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'
