include:
  - 'templates/.gitlab-ci-mainnet.yml'
  - 'templates/.gitlab-ci-optimism.yml'
  - 'templates/.gitlab-ci-arbitrum.yml'
  - 'templates/.gitlab-ci-avalanche.yml'

image: node:18-buster

default:
  tags:
    - docker
  cache:
    key: ${CI_PROJECT_PATH_SLUG}
    paths:
      - node_modules/
      - artifacts/
      - cache/
  before_script:
    - npm install

stages:
  - build
  - test-mainnet
  - test-optimism
  - test-arbitrum
  - test-avalanche
  - analysis
  - certora

build:
  stage: build
  script:
    - npm run build

# Certora Prover CI
.job_template: &certora-configuration
  stage: certora
  image: 376433862203.dkr.ecr.us-east-1.amazonaws.com/certora-ci-base:latest
  allow_failure: true
  before_script:
    - ./specs/scripts/applyHarnesses.sh

certora_develop:
  <<: *certora-configuration
  script:
    - python3 scripts/certora_ci.py -r diff
  rules: # Trigger it when merge to develop branch
    - if: '$CI_COMMIT_TITLE =~ /^Merge branch/ && $CI_COMMIT_BRANCH == "develop"'

certora_release:
  <<: *certora-configuration
  script:
    - python3 scripts/certora_ci.py -r all
  rules: # Trigger it when checkout release branch
    - if: '$CI_COMMIT_BRANCH =~ /^release/ && $CI_COMMIT_BEFORE_SHA == "0000000000000000000000000000000000000000"'

# Analysis
analysis_slither:
  stage: analysis
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install slither-analyzer && pip3 install solc-select
    - npm run analysis
