# Test Template
.job_template: &test-arbitrum-configuration
  stage: test-arbitrum
  before_script:
    - npx patch-package --patch-dir patch
  script:
    - apt-get update && apt-get install -y netcat
    - RUNNER_COUNT=4
    - FILES=( $(find -H -L ./test/* -regex "^.*.test.js") )
    - len=${#FILES[@]}
    - >
      for (( i=0; i<${RUNNER_COUNT}; i+=1 )); do
          RUNNER_TEST_CNTS[$i]=0
      done
    - >
      for (( i=0; i<${len}; i+=1 )); do
          TestCases[$i]=$(grep -o " it" ${FILES[$i]} | wc -l)
      done
    - >
      for ((i = 0; i<${len}; i++))
      do
          for((j = 0; j<${len}-i-1; j++))
          do
              if [ ${TestCases[j]} -lt ${TestCases[$((j+1))]} ]
              then
                  # swap
                  temp=${TestCases[j]}
                  TestCases[$j]=${TestCases[$((j+1))]}
                  TestCases[$((j+1))]=$temp

                  temp=${FILES[j]}
                  FILES[$j]=${FILES[$((j+1))]}
                  FILES[$((j+1))]=$temp
              fi
          done
      done
    - MIN=${RUNNER_TEST_CNTS[0]}
    - MINIDX=0
    - >
      for (( i=0; i<${len}; i+=1 )); do
          for j in ${!RUNNER_TEST_CNTS[@]};
          do
              if [ ${MIN} -gt ${RUNNER_TEST_CNTS[$j]} ]
              then
                  MIN=${RUNNER_TEST_CNTS[${j}]}
                  MINIDX=${j}
              fi
          done

          UNITTEST_FILES[$MINIDX]+=' '"${FILES[$i]}"
          RUNNER_TEST_CNTS[$MINIDX]=`expr ${TestCases[$i]} + ${RUNNER_TEST_CNTS[$MINIDX]}`
          MIN=${RUNNER_TEST_CNTS[$MINIDX]}
      done
    - ETH_MAINNET_NODE=https://rpc.ankr.com/arbitrum CHAIN_ID=42161 npm run test ${UNITTEST_FILES[${JOB_INDEX}]}

arbitrum_test_0:
  variables:
    JOB_INDEX: 0
  <<: *test-arbitrum-configuration

arbitrum_test_1:
  variables:
    JOB_INDEX: 1
  <<: *test-arbitrum-configuration

arbitrum_test_2:
  variables:
    JOB_INDEX: 2
  <<: *test-arbitrum-configuration

arbitrum_test_3:
  variables:
    JOB_INDEX: 3
  <<: *test-arbitrum-configuration

arbitrum_test_4:
  variables:
    JOB_INDEX: 4
  <<: *test-arbitrum-configuration

arbitrum_test_5:
  variables:
    JOB_INDEX: 5
  <<: *test-arbitrum-configuration

arbitrum_test_6:
  variables:
    JOB_INDEX: 6
  <<: *test-arbitrum-configuration

arbitrum_test_7:
  variables:
    JOB_INDEX: 7
  <<: *test-arbitrum-configuration

arbitrum_test_8:
  variables:
    JOB_INDEX: 8
  <<: *test-arbitrum-configuration

arbitrum_test_9:
  variables:
    JOB_INDEX: 9
  <<: *test-arbitrum-configuration

arbitrum_test_10:
  variables:
    JOB_INDEX: 10
  <<: *test-arbitrum-configuration

arbitrum_test_11:
  variables:
    JOB_INDEX: 11
  <<: *test-arbitrum-configuration

arbitrum_test_12:
  variables:
    JOB_INDEX: 12
  <<: *test-arbitrum-configuration

arbitrum_test_13:
  variables:
    JOB_INDEX: 13
  <<: *test-arbitrum-configuration

arbitrum_test_14:
  variables:
    JOB_INDEX: 14
  <<: *test-arbitrum-configuration

arbitrum_test_15:
  variables:
    JOB_INDEX: 15
  <<: *test-arbitrum-configuration
