arbitrum_test_0:
  variables:
    JOB_INDEX: 0
    RUNNER_COUNT: 4
    RPC_URL: ${ARBITRUM_RPC_URL}
    CHAIN_ID: 42161
  extends: .test_template

arbitrum_test_1:
  variables:
    JOB_INDEX: 1
    RUNNER_COUNT: 4
    RPC_URL: ${ARBITRUM_RPC_URL}
    CHAIN_ID: 42161
  extends: .test_template

arbitrum_test_2:
  variables:
    JOB_INDEX: 2
    RUNNER_COUNT: 4
    RPC_URL: ${ARBITRUM_RPC_URL}
    CHAIN_ID: 42161
  extends: .test_template

arbitrum_test_3:
  variables:
    JOB_INDEX: 3
    RUNNER_COUNT: 4
    RPC_URL: ${ARBITRUM_RPC_URL}
    CHAIN_ID: 42161
  extends: .test_template
